version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.5
