before:
  hooks:
  
builds:
  - 
    id: build
    main: cmd/
    binary: sver
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s 
      - -w 
      - -X main.ver={{.Version}} 
      - -X main.commit={{.ShortCommit}} 
      - -X main.date={{.Date}} 
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE.md
      - README.md
    name_template: "sver{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: aserto-dev
    name: sver

  draft: false
  prerelease: false
  name_template: "sver {{.Tag}}"

brews:
  -
    name: sver

    tap:
      owner: aserto-dev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP }}"

    url_template: "https://github.com/aserto-dev/sver/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://aserto.com/"

    description: "sver semantic version calculator"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/sver version"

    install: |
      bin.install "sver"
